#ifndef APP_API_CONFIG_HANDLER_WIFI_H
#define APP_API_CONFIG_HANDLER_WIFI_H

extern const httpd_uri_t app_api_config_handler_wifi_get_uri;
extern const httpd_uri_t app_api_config_handler_wifi_post_uri;

#endif //APP_API_CONFIG_HANDLER_WIFI_H
