#ifndef APP_API_CONFIG_HANDLER_UPGRADE_H
#define APP_API_CONFIG_HANDLER_UPGRADE_H

extern const httpd_uri_t app_api_config_handler_upgrade_get_uri;
extern const httpd_uri_t app_api_config_handler_upgrade_post_uri;

#endif //APP_API_CONFIG_HANDLER_UPGRADE_H
