name: IDF Build
on:
  push:
    branches: [ master ]
jobs:
  idf-build:
    runs-on: ubuntu-latest
    container:
      image: "espressif/idf:v5.2.1"
    steps:
      - name: Build Application
        run: idf.py build
