name: IDF Build
on:
  push:
    branches: [ master ]

  pull_request:
    types:
      - opened
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build Application
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2.2
          target: esp32s3
          path: "./"